### ISSUE TITLE
Replace Favicon

### ISSUE THREAD

**Issue by J-Hust** [code-map/capstone-1804#145]

**Comment by jamigibbs** [comment]
This should already be done so I'm closing but re-open if the intention was to replace it with something else:
![Screen Shot 2018-07-05 at 8.29.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b156ecf1bff6200127360b3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246454f66b7191a370f110224f5b595edd3c4a4356bcbbd671f3e57862804e0ebfd33c0d70c76b12f9ed854dbd01ba238a4b83beba8d4ed2f42f67b6d5db1063474f4dcbed5727a19141c95df54be64452a0133561e5702431.png)
