### ISSUE TITLE
Path builder / Private Path 

### ISSUE THREAD

**Issue by maubertw** [code-map/capstone-1804#8]
can add/remove/reorder/edit module

show current modules on the path

show path name & description?

**Comment by jamigibbs** [comment]
Resource: open graph scraper https://www.npmjs.com/package/open-graph-scraper

**Comment by jamigibbs** [comment]
- [ ] Check if path name already exists
- [ ] Create new unique path (draft status)
- [ ] Add resources to new path
- [ ] Re-order resources
